name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
    - run: go version
    - name: Install gox
      run: go install github.com/mitchellh/gox@latest
    - name: Smoke-test gox
      run: gox -h
    - name: gox the things
      run: gox -osarch='darwin/arm64 darwin/amd64 linux/386 linux/amd64 linux/arm freebsd/386 freebsd/amd64 openbsd/386 openbsd/amd64 windows/386 windows/amd64 freebsd/arm netbsd/386 netbsd/amd64 netbsd/arm linux/s390x linux/mips64 linux/mips64le linux/mips linux/mipsle' -parallel=1 -output=l1-{{.OS}}-{{.Arch}}-${GITHUB_REF_NAME}
    - name: List files
      run: ls -al
    - name: Execute bit
      run: chmod +x l1-*-*-*
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "l1-*-*-*"
        token: ${{ secrets.GITHUB_TOKEN }}
