name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
    - run: go version
    - name: Install gox
      run: go install github.com/mitchellh/gox@latest
    - name: Smoke-test gox
      run: gox -h
    - name: gox the things
      run: gox -osarch='!darwin/386 linux/mipsle' -parallel=18 -output=l1-{{.OS}}-{{.Arch}}-${GITHUB_REF_NAME}
    - name: List files
      run: ls -al
    - uses: actions/upload-artifact@v3
    - name: Upload Binaries
      with:
        path: */l1-*-${GITHUB_REF_NAME}


