name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install gox
      run: go install github.com/mitchellh/gox@latest
    - name: Test gox
      run: echo path $PATH gopath $GOPATH end
      
